apiVersion: v1
kind: Service
metadata:
  name: nkfilms-service
  labels:
    app: nkfilms
spec:
  type: LoadBalancer      # Exposes app to the internet
  selector:
    app: nkfilms
  ports:
    - protocol: TCP
      port: 80            # External port
      targetPort: 80      # Container port
